apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret
  labels:
    app: flask-app
type: Opaque
data:
  # Base64 encoded values
  APP_ENV: REVWRUxPUE1FTlQ=  # "DEVELOPMENT" in base64
  APP_PASSWORD: MDY4OTExOGE4NjQ1ZDk4YzUxZDM3YWUxMjU1ZmJlYmU=  # "0689118a8645d98c51d37ae1255fbebe" in base64
